### ISSUE TITLE
[Updatable/JSGen] @default rompe el metamodelo

### ISSUE THREAD

**Issue by jserranohidalgo** [jserranohidalgo/test-trac#1]
**Reported by jlopez on 13 Sep 2013 08:19 UTC**
Al declararse un valor ''default'' con los siguientes tipos:

```

trait A { val a1: Set[@default("HashSet[Int](Int])()") }

implicit val A = builder[A]

```

se rompe el generador de los prototipos JavaScript:

```
scala.tools.reflect.ToolBoxError: reflective typecheck has failed: not found: value HashSet
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typeCheck$1.apply(ToolBoxFactory.scala:175)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typeCheck$1.apply(ToolBoxFactory.scala:167)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$10.apply(ToolBoxFactory.scala:144)
...
```

**Comment by jserranohidalgo** [comment]
**Modified by jlopez on 13 Sep 2013 08:19 UTC**

**Comment by jserranohidalgo** [comment]
**Comment by jlopez on 13 Sep 2013 08:30 UTC**
El problema reside en que el valor de la anotacin se est generando en ''runtime'' mediante un ''toolbox'', concrtamente en ''org.hablapps.jsgen.JSGen''. En ese punto no est importado ''scala.collection.immutable.HashSet'' y el ''toolbox'' se queja de ello. La solucin bsica pasa por importar dicho tipo en el fichero JSGen, lo cual no tiene mucho sentido ya que tambin deberamos importar todos los tipos que podran ser utilizados por ''updatable'' (y no se usaran en el 99% de los casos). Por tanto, la mejor solucin que hemos encontrado pasa por utilizar rutas completas en el parmetro de @default:

```
trait A { val a1: Set[@default("scala.collection.immutable.HashSet[Int](Int])()") }

implicit val A = builder[tambin que la inferencia de tipos no funciona bien en este contexto, y es condicin indispensable que los tipos parametrizados ya estn resueltos (por ejemplo: ''Set'''[Int](A]
```

Mencionar)''''').
